### PR TITLE
Mac support

### LINKED ISSUE #1: Mac support
I tried to add Mac support and failed. I have no idea why the github action doesn't build the mac version

Here's the branch where I tried to add support: <https://github.com/decompals/mips-binutils-egcs-2.9.5/tree/mac-support>

### PR DESCRIPTION
**Pull request by Alto1772**
~~One more thing in this change, I've moved CFLAGS from `make` onto the `./configure` at execution.~~ Y'know what? Scratch that...
This might require rigorous testing I hope... Fixes #1

### CODE REVIEW

**Comment by cadmic** [comment]
I tried this locally and I needed this patch:

```diff
--- a/ld/ldlex.l
+++ b/ld/ldlex.l
@@ -76,9 +76,15 @@ static unsigned int lineno_stack[MAX_INCLUDE_DEPTH];
 static unsigned int include_stack_ptr = 0;
 static int vers_node_nesting = 0;

+#ifdef DARWIN
+#define YY_SIZE_T yy_size_t
+#else
+#define YY_SIZE_T int
+#endif
+
 static YY_BUFFER_STATE yy_create_string_buffer PARAMS ((const char *string,
                                                        size_t size));
-static void yy_input PARAMS ((char *, int *result, int max_size));
+static void yy_input PARAMS ((char *, YY_SIZE_T *result, int max_size));

 static void comment PARAMS ((void));
 static void lex_warn_invalid PARAMS ((char *where, char *what));
@@ -581,7 +587,7 @@ ldlex_popstate ()
 static void
 yy_input (buf, result, max_size)
      char *buf;
-     int *result;
+     YY_SIZE_T *result;
      int max_size;
 {
   *result = 0;
```

Otherwise things went smoothly, I tested on the ultralib iQue branch and it seemed to work

File: libiberty/strerror.c [hunk 1]
```diff
@@ -460,12 +460,20 @@ static int num_error_names = 0;
 static int sys_nerr;
 static const char **sys_errlist;
 
+#else
+#ifdef DARWIN
```
Comment (AngheloAlf) [inline libiberty/strerror.c]:
```suggestion
#elif defined(DARWIN)
```
Would remove the need for an extra trailing `#endif`

**Review by AngheloAlf — COMMENTED** [review]
Another nit besides the patch posted by cadmic
